# Generated by Django 2.1.3 on 2020-06-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(
                choices=[('F', 'Feminino'), ('M', 'Masculino'),
                         ('O', 'Outros')], max_length=1),
        ),
    ]
