# Generated by Django 2.2 on 2020-06-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Address'),
        ),
    ]
