# Generated by Django 2.2 on 2020-06-28 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0004_client_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('order_date',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('status', models.CharField(
                    choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'),
                             ('E', 'Saiu para entrega')], max_length=1)),
                ('observations',
                 models.CharField(blank=True, max_length=50, null=True)),
                ('client',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='clients.Client')),
            ],
        ),
    ]
