# Generated by Django 2.2 on 2020-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='clients.Product'),
        ),
    ]
