# Generated by Django 2.2 on 2020-06-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200628_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
