# Generated by Django 2.2 on 2020-06-30 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0007_client_lastname'),
    ]

    operations = [
    ]
