# Generated by Django 2.2 on 2020-06-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200630_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
