# Generated by Django 2.2 on 2020-07-01 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0009_auto_20200630_2333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='cliente',
        ),
    ]
